dbfilename redis_queue.rdb
dir /home/ali/Masaüstü/istoc.com/tradehubback/config/pids
pidfile /home/ali/Masaüstü/istoc.com/tradehubback/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /home/ali/Masaüstü/istoc.com/tradehubback/config/redis_queue.acl
