dbfilename redis_queue.rdb
dir /home/metin/Desktop/istoc.com/tradehubback/config/pids
pidfile /home/metin/Desktop/istoc.com/tradehubback/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /home/metin/Desktop/istoc.com/tradehubback/config/redis_queue.acl
